# Generated by Django 5.0 on 2024-01-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSWebapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymaster',
            name='city',
            field=models.CharField(choices=[('Ahmedabad', 'Ahmedabad'), ('Gandhinagar', 'Gandhinagar'), ('Rajkot', 'Rajkot'), ('Surat', 'Surat')], max_length=25),
        ),
        migrations.AlterField(
            model_name='facultymaster',
            name='department',
            field=models.CharField(choices=[('BCA', 'BCA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='facultymaster',
            name='designation',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Lecturer', 'Lecturer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='facultymaster',
            name='facphoto',
            field=models.FileField(max_length=50, upload_to=''),
        ),
    ]
