# Generated by Django 5.0 on 2024-01-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSWebapp', '0002_alter_facultymaster_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymaster',
            name='area',
            field=models.CharField(choices=[('Ghatlodia', 'Ghatlodia'), ('Ranip', 'Ranip'), ('Naranpura', 'Naranpura'), ('Chandlodia', 'Chandlodia')], max_length=25),
        ),
    ]
