# Generated by Django 5.0 on 2024-01-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSWebapp', '0003_alter_facultymaster_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMaster',
            fields=[
                ('stid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='SID')),
                ('stdenno', models.BigIntegerField()),
                ('stdfname', models.CharField(max_length=25)),
                ('stdmname', models.CharField(max_length=25)),
                ('stdlname', models.CharField(max_length=25)),
                ('stdemailid', models.CharField(max_length=50)),
                ('stdscontactno', models.BigIntegerField()),
                ('stdpcontactno', models.BigIntegerField()),
                ('designation', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50)),
                ('department', models.CharField(choices=[('BCA', 'BCA')], max_length=50)),
                ('stdaddress', models.CharField(max_length=100)),
                ('stdcity', models.CharField(choices=[('Ahmedabad', 'Ahmedabad'), ('Gandhinagar', 'Gandhinagar'), ('Rajkot', 'Rajkot'), ('Surat', 'Surat')], max_length=25)),
                ('stdarea', models.CharField(choices=[('Ghatlodia', 'Ghatlodia'), ('Ranip', 'Ranip'), ('Naranpura', 'Naranpura'), ('Chandlodia', 'Chandlodia')], max_length=25)),
                ('stdphoto', models.FileField(max_length=50, upload_to='')),
            ],
            options={
                'db_table': 'studentmaster',
            },
        ),
    ]
