# Generated by Django 5.0 on 2024-01-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMSWebapp', '0004_studentmaster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmaster',
            old_name='department',
            new_name='stddepartment',
        ),
        migrations.RenameField(
            model_name='studentmaster',
            old_name='designation',
            new_name='stdsemester',
        ),
    ]
