# Generated by Django 5.0 on 2024-01-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSWebapp', '0005_rename_department_studentmaster_stddepartment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMaster',
            fields=[
                ('atid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ATID')),
                ('id', models.IntegerField()),
                ('stdphoto', models.CharField(max_length=50)),
                ('stdenno', models.BigIntegerField()),
                ('stdname', models.CharField(max_length=100)),
                ('stdsemester', models.IntegerField()),
                ('atdate', models.CharField(max_length=25)),
                ('atstatus', models.CharField(choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=25)),
            ],
            options={
                'db_table': 'attendancemaster',
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('statid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='STATID')),
                ('stdenno', models.BigIntegerField()),
                ('stname', models.CharField(max_length=50)),
                ('atstatus', models.CharField(choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=25)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
