# Generated by Django 5.0 on 2024-01-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSWebapp', '0007_alter_attendancemaster_stdenno'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMaster',
            fields=[
                ('matid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='MATID')),
                ('id', models.IntegerField()),
                ('stdsemester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10)),
                ('matsubj', models.CharField(choices=[('MATHS', 'MATHS'), ('DATA-BASE MANAGEMENT SYSTEM', 'DATA-BASE MANAGEMENT SYSTEM'), ('C PROGRAMMING', 'C PROGRAMMING'), ('FINANCIAL ACCOUNTING AND MANAGEMENT', 'FINANCIAL ACCOUNTING AND MANAGEMENT'), ('OPOL', 'OPOL'), ('BUSSINESS ECONOMICS', 'BUSSINESS ECONOMICS'), ('COMPUTER GRAPHICS', 'COMPUTER GRAPHICS'), ('OPERATING SYSTEM', 'OPERATING SYSTEM'), ('JAVA', 'JAVA'), ('COMPUTER NETWORKS', 'COMPUTER NETWORKS')], max_length=50)),
                ('matfile', models.FileField(max_length=50, upload_to='')),
            ],
            options={
                'db_table': 'materialmaster',
            },
        ),
    ]
