# Generated by Django 5.0 on 2024-02-19 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMSWebapp', '0012_eventmaster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmaster',
            old_name='eventdate',
            new_name='evdate',
        ),
        migrations.RenameField(
            model_name='eventmaster',
            old_name='eventname',
            new_name='evname',
        ),
    ]
