# Generated by Django 5.0 on 2024-02-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSWebapp', '0013_rename_eventdate_eventmaster_evdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesMaster',
            fields=[
                ('feid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='FID')),
                ('stdsemester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10)),
                ('feamt', models.BigIntegerField()),
            ],
            options={
                'db_table': 'feesmaster',
            },
        ),
    ]
