# Generated by Django 5.0 on 2024-02-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSWebapp', '0014_feesmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentfeesmaster',
            fields=[
                ('stfeid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='STFEID')),
                ('stdenno', models.BigIntegerField()),
                ('stdname', models.CharField(max_length=100)),
                ('stdsemester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10)),
                ('feamt', models.BigIntegerField()),
            ],
            options={
                'db_table': 'studentfeesmaster',
            },
        ),
    ]
